# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-10 06:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_auto_20181221_0540'),
        ('student', '0017_userprofile_phone'),
    ]

    operations = [
    ]
