# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-16 09:29
from __future__ import unicode_literals

from django.db import migrations
import student.fields


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_merge_20190510_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=student.fields.AESCharField(max_length=60, null=True, verbose_name=b'Phone'),
        ),
    ]
