# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-13 09:27
from __future__ import unicode_literals

from django.db import migrations
import student.fields
import student.hasher


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_hash_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=student.fields.HashCharField(hasher=student.hasher.AESCipher, max_length=256, null=True),
        ),
    ]
