# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-10 06:17
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.models import User


def forwards_func(apps, schema_editor):
    users = User.objects.all()        
    for user in users:
        user.save(update_fields=["email"])


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0022_hash_userprofile_phone'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
